/* ************************************************************************** *
 * Chess Tools - Magic Bitboard Generator                                     *
 * Search for magic numbers                                                   *
 * ************************************************************************** */

#include "generate_scenario.h"

namespace magic_bitboard_generator::generate_scenario {

auto generate_headers(const Args &args) -> void {
    Database database = DatabaseReader{args.database}.read();
    HeaderFile header_file{args.output};
    header_file.write_header();
    header_file.write_data_set("rook", database.rook_records());
    header_file.write_data_set("bishop", database.bishop_records());
    header_file.write_footer();
}

auto HeaderFile::write_header() -> void {
    m_file << R"(/* Magic Bitboard Data
 * This file was generated by magic_bitboard_generator.
 */

#ifndef CHESSCORE_MAGIC_BITBOARD_DATA_H
#define CHESSCORE_MAGIC_BITBOARD_DATA_H

#include "chesscore/magic.h"

namespace chesscore {

)";
}

auto HeaderFile::write_data_set(const std::string &piece_name, const std::vector<Record> &records) -> void {
    start_data_set(piece_name);
    for (const auto &record : records) {
        write_record(record);
    }
    end_data_set();
}

auto HeaderFile::start_data_set(const std::string &piece_name) -> void {
    m_file << "inline constexpr MagicDataSet magic_" << piece_name << "_data{\n";
}

auto HeaderFile::write_record(const Record &record) -> void {
    m_file << "\tMagicData{.magic_number = " << std::format("0x{:016x}", record.magics().magic_number)
           << ", .max_index = " << record.stats().max_index << ", .shift = " << record.magics().shift << "},\n";
}

auto HeaderFile::end_data_set() -> void {
    m_file << "};\n\n";
}

auto HeaderFile::write_footer() -> void {
    m_file << R"(
} // namespace chesscore

#endif
)";
}

} // namespace magic_bitboard_generator::generate_scenario
